export const VOICEVOX_SPEAKERS = [
  { id: 3, name: "ずんだもん（ノーマル）" },
  { id: 1, name: "四国めたん（ノーマル）" },
  { id: 2, name: "ずんだもん（あまあま）" },
  { id: 0, name: "四国めたん（あまあま）" },
  { id: 6, name: "ずんだもん（セクシー）" },
  { id: 4, name: "四国めたん（セクシー）" },
  { id: 7, name: "ずんだもん（ツンツン）" },
  { id: 5, name: "四国めたん（ツンツン）" },
  { id: 20, name: "WhiteCUL（ノーマル）" },
  { id: 23, name: "後鬼（人間ver.）" },
  { id: 21, name: "後鬼（ワーウルフver.）" },
  { id: 8, name: "春日部つむぎ" },
  { id: 9, name: "雨晴はう" },
  { id: 10, name: "波音リツ" },
  { id: 11, name: "玄野武宏" },
  { id: 12, name: "白上虎太郎" },
  { id: 13, name: "青山龍星" },
  { id: 14, name: "冥鳴ひまり" },
  { id: 16, name: "九州そら（ノーマル）" },
];